# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:14
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationActivationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(blank=True, help_text='Choice your profile picture.', max_length=255, null=True, verbose_name='Profile Picture')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Select your gender.', max_length=1, verbose_name='Gender')),
                ('birthday', models.DateField(help_text='Enter your date of birth.', verbose_name='Birthday')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserDetail',
                'verbose_name_plural': 'UserDetails',
            },
        ),
    ]
