# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateField(help_text='Enter your date of birth.', null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Select your gender.', max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
