# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 11:04
from __future__ import unicode_literals

import apps.userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_registrationactivationsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationactivationemail',
            name='time_expired',
            field=models.DateTimeField(default=apps.userprofile.models.default_time_expired),
        ),
        migrations.AddField(
            model_name='registrationactivationsms',
            name='time_expired',
            field=models.DateTimeField(default=apps.userprofile.models.default_time_expired),
        ),
    ]
